# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from commonfate.paths.api_v1_admin_requests_request_id.get import AdminGetRequest
from commonfate.paths.api_v1_requests_request_id_cancel.post import UserCancelRequest
from commonfate.paths.api_v1_requests.post import UserCreateRequest
from commonfate.paths.api_v1_requests_request_id_access_instructions.get import UserGetAccessInstructions
from commonfate.paths.api_v1_access_rules_rule_id.get import UserGetAccessRule
from commonfate.paths.api_v1_access_rules_rule_id_approvers.get import UserGetAccessRuleApprovers
from commonfate.paths.api_v1_requests_request_id_access_token.get import UserGetAccessToken
from commonfate.paths.api_v1_users_me.get import UserGetMe
from commonfate.paths.api_v1_requests_request_id.get import UserGetRequest
from commonfate.paths.api_v1_users_user_id.get import UserGetUser
from commonfate.paths.api_v1_access_rules.get import UserListAccessRules
from commonfate.paths.api_v1_requests_request_id_events.get import UserListRequestEvents
from commonfate.paths.api_v1_requests.get import UserListRequests
from commonfate.paths.api_v1_requests_request_id_review.post import UserReviewRequest
from commonfate.paths.api_v1_requests_requestid_revoke.post import UserRevokeRequest


class EndUserApi(
    AdminGetRequest,
    UserCancelRequest,
    UserCreateRequest,
    UserGetAccessInstructions,
    UserGetAccessRule,
    UserGetAccessRuleApprovers,
    UserGetAccessToken,
    UserGetMe,
    UserGetRequest,
    UserGetUser,
    UserListAccessRules,
    UserListRequestEvents,
    UserListRequests,
    UserReviewRequest,
    UserRevokeRequest,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
